version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
