name: CI

on: push

jobs:
  cpp:
    name: "${{ matrix.os }} :: C++"
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Make build directory
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DBUILD_DOCS=OFF -DBUILD_TESTING=ON -DBUILD_PYTHON=OFF

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build .

      - name: Run tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ctest

  python:
    name: "${{ matrix.os }} :: Python ${{ matrix.python-version }}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Python bindings using pip
        run: python -m pip install .[test] -v

      - name: Run Python tests
        run: python -m pytest -v
